on:
  push:
    branches:
      - master
name: 🚀 Deploy correspondencia
jobs:
  web-deploy:
    name: 🎉 Levantando Software Correspondencia
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obteniendo ultima version del codigo
        uses: actions/checkout@v2.3.2

      - name: 📂 sincronizando archivos
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: URL_SERVIDOR
          username: ${{ secrets.ftp_username }} #CREAR SECRET FTP_USERNAME
          password: ${{ secrets.ftp_password }} #CREAR SECRET FTP_USERNAME
          server-dir: /public_html/CARPETA/